### ISSUE TITLE
Link em publicação.

### ISSUE THREAD

**Issue by creativedean** [adlerluiz/tabnews-mobile#21]
Hi,

Quando alguma publicação usa algum link para outra página do Tabnews ao clicar no link a pagina abre fora do app.
Mesmo alterando nas configurações do app para abrir links no próprio app, ele abre o browser interno.

Teria como implementar para abrir como uma navegação normal no próprio app?

Tentei alterar as configurações de abrir links padrões em cada app no próprio Android, iria adicionar o tabnwens.com.br/* para o app, porem sem sucesso, pois o app não aparece nas listas disponíveis.

![Screenshot_2023-04-05-20-57-54-286_com adlerluiz tabnews](https://user-images.githubusercontent.com/109149847/230199778-f93b864a-3c39-48a8-819b-6b0da0f731e4.jpg)
![Screenshot_2023-04-05-20-58-02-926_com adlerluiz tabnews](https://user-images.githubusercontent.com/109149847/230199781-46b44696-1c6e-4daa-8539-e49242e5a177.jpg)

Android 12
Redmi Note 11

**Comment by Suburbanno** [comment]
@adlerluiz existe planos para voltar ao desenvolvimento do app?

**Comment by adlerluiz** [comment]
@creativedean Isso já é algo que percebi e está no roadmap de implementações, em breve vou implementar!

@Suburbanno sim, semana que vem, voltarei a mexer no app

**Comment by Suburbanno** [comment]
@adlerluiz alguma atualização sobre?

**Comment by eliasamaral** [comment]
@Suburbanno você quer dizer links de postagens próprias do Tab? Meu problema é que todo link, mesmo sendo de algo externo, abre em um navegador interno que não aparece a barra de opções, e isso me impede de ter a função de  "abrir no Chrome por exemplo". 


Exemplo de um link clicado no gmail. Que possui um comportamento ideial, imagino...

![Screenshot_2023-09-30-11-01-42-44_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/adlerluiz/tabnews-mobile/assets/35604093/e06064fe-0f9d-42e6-a61e-cfedd604a9c6)

Agora no app do Tab...

![Screenshot_2023-09-30-11-03-00-39_ac371f7a9f296973acecaccb750a87a5.jpg](https://github.com/adlerluiz/tabnews-mobile/assets/35604093/cd5c8835-69de-4204-ab80-9c126b2bf3df)

**Comment by Suburbanno** [comment]
> @Suburbanno você quer dizer links de postagens próprias do Tab? Meu problema é que todo link, mesmo sendo de algo externo, abre em um navegador interno que não aparece a barra de opções, e isso me impede de ter a função de "abrir no Chrome por exemplo".


@eliasamaral Ele fala sobre os links de tabnews -> tabnews, para abrir de forma normal, nativa do App. Já os links externos de fato, abrem no browser interno de forma limitada, o que é bem ruim.

**Comment by eliasamaral** [comment]
Resolvi nas configurações do app. Erro besta de quem acabou de instalar o app. Mas a questão dos links internos é genuína.

**Comment by adlerluiz** [comment]
Melhoria feita na branch **feature/links** e em breve estará disponível

Todo link do tabnews será interpretado, onde:

https://www.tabnews.com.br/user e https://www.tabnews.com.br/user/publicacao

abrirá dentro do app de forma nativa, qualquer outro link diferente seguirá com o comportamento de abrir no navegador.
