### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by ivofernandes** [adlerluiz/tabnews-mobile#6]
Oi, reparei no linkedin de estarem a falar em te ajudar a fazer o lançamento para iOS. Precisas de ajuda? Eu tenho conta de apple onde poderia publicar se por acaso não quiseres criar uma conta de propósito

**Comment by adlerluiz** [comment]
legal, agradeço sua ajuda, tem algum lugar que possamos conversar melhor? um discord ou o que preferir

**Comment by ivofernandes** [comment]
Sim podemos falar no discord da tabnews se quiseres.

Ou se for mais fácil adiciona no linkedin

https://www.linkedin.com/in/ivofernandes84

**Comment by adlerluiz** [comment]
pode ser, entrei lá, quando puder conversamos
