### ISSUE TITLE
Enable roles for moderators

### ISSUE THREAD

**Issue by gabrielsozinho** [adlerluiz/tabnews-mobile#7]
Hey Adler, I don't know if I should write this issue in English or Portuguese, but I decided to do it in English. 😅

I'm a moderator of TabNews and one feature that I missed was exactly the moderation ones. I can't edit/delete anyone else's content and I can't nuke them either (In the web version I can).

I think a solution to this is check if the user has the `update:content:others` (to edit and delete contents) and the `ban:user` (to nuke other users) features, then save that locally. Later, if the user has it, enable buttons to do that.

I know that this is not a preferred feature and that it can be a little annoying to implement, but because this is one of the best unofficial TabNews mobile apps, I would like to see it implemented. 👍🏻

*obs: sorry for my English.*

**Comment by adlerluiz** [comment]
Hello @gabrielsozinho, I hadn't even thought of this idea of moderation, the app was a way of viewing and posting for the common user, but now that you've given me this idea, I like it, and I'm going to add this feature 😄.

I already uploaded the tabnews locally to perform the tests.

Thanks!!

**Comment by adlerluiz** [comment]
will be available in the next release!
